- backend/.gitignore
- backend/pyproject.toml
- backend/requirements.txt
- backend/src/core/__init__.py
- backend/src/core/rembg.py
- backend/src/main.py
- backend/src/routers/__init__.py
- backend/src/routers/extract.py
- backend/src/schemas/__init__.py
- backend/src/schemas/extract.py
> add: rembg 実行エンドポイント作成

- frontend/src/app/fetch-test/layout.tsx
- frontend/src/app/level-select/layout.tsx
> 不要な layout.tsx を削除

- docker-compose.develop.yml
> 開発環境で https を有効にする（http では Web カメラにアクセスできないため）

- backend/src/main.py
- backend/src/routers/extract.py
> ディレクトリが存在しない場合のエラーを修正

- backend/src/routers/extract.py
- backend/src/schemas/extract.py
> base64 画像を受け取るように変更

- .vscode/settings.json
- frontend/.prettierrc
- frontend/src/components/Message.tsx
> update: ポップアップ呼び出し時に type と message を指定するよう変更

- frontend/src/app/confirm-silhouette/page.tsx
- frontend/src/app/take-picture/Camera.tsx
- frontend/src/app/take-picture/page.tsx
> add: シルエット撮影画面

- frontend/src/app/take-picture/Camera.tsx
> fix: 撮影サイズを修正

- frontend/src/app/take-picture/Camera.tsx
> add: 撮影画面に戻るボタンを追加

- Makefile
> fix: Makefile の build と up コマンドに docker-compose ファイルの指定を追加

- frontend/src/app/layout.tsx
> head タイトル修正

- frontend/src/app/take-picture/Camera.tsx
> iPhone video 修正

- backend/src/schemas/monster.py
> level の typehint を int ではなく 1, 2, 3 に限定

- backend/src/routers/monster.py
- backend/src/types/__init__.py
- backend/src/types/monster.py
> DB に保存されているモンスター画像を返すエンドポイント

- backend/src/__init__.py
- backend/src/core/rembg.py
- backend/src/routers/extract.py
- backend/src/routers/monster.py
- backend/src/utils.py
> png ⇔ base64 間の変換処理を関数化

- backend/src/__init__.py
- backend/src/cruds/__init__.py
- backend/src/cruds/monster.py
- backend/src/routers/__init__.py
- backend/src/routers/monster.py
- backend/src/types/monster.py
- backend/src/utils.py
> 指定した id のモンスターを取得する

- frontend/src/app/select-silhouette/page.tsx
> シルエット選択画面の作成

- backend/src/cruds/__init__.py
- backend/src/cruds/silhouette.py
- backend/src/main.py
- backend/src/routers/__init__.py
- backend/src/routers/monster.py
- backend/src/routers/silhouette.py
- backend/src/types/__init__.py
- backend/src/types/silhouette.py
> 指定された id のシルエット画像を返すエンドポイントの作成

- frontend/src/app/confirm-silhouette/page.tsx
- frontend/src/app/select-silhouette/page.tsx
- frontend/src/app/take-picture/Camera.tsx
- frontend/src/app/take-picture/page.tsx
- frontend/src/components/Centering.tsx
> refactor: カメラコンポーネント

- backend/src/routers/__init__.py
- backend/src/routers/monster.py
- backend/src/routers/silhouette.py
- backend/src/types/monster.py
> monster / silhouette CRUD 関数名修正

- backend/src/cruds/monster.py
- backend/src/models/image.py
- backend/src/models/monster.py
- backend/src/models/silhouette.py
- backend/src/models/user.py
- backend/src/routers/extract.py
- backend/src/routers/monster.py
- backend/src/routers/silhouette.py
- backend/src/types/__init__.py
- backend/src/types/extract.py
- backend/src/types/monster.py
- backend/src/types/silhouette.py
- backend/src/utils.py
> バックエンド 型周り リファクタリング

- backend/src/core/__init__.py
- backend/src/core/merge_silhouettes.py
- backend/src/routers/__init__.py
- backend/src/routers/monster.py
> `_merge_silhouettes` 関数を `core/` 以下へ移動

- backend/src/models/image.py
- backend/src/models/monster.py
- backend/src/models/silhouette.py
- backend/src/types/extract.py
> FE / BE / DB 間の制約追加

- backend/src/__init__.py
- backend/src/routers/silhouette.py
- backend/src/utils.py
- frontend/src/app/take-picture/page.tsx
> 撮影画面でシルエットを中央に表示させる

- backend/src/routers/silhouette.py
- frontend/src/app/take-picture/page.tsx
> シルエット画像の透過処理を BE ではなく FE で行う

- frontend/src/app/take-picture/page.tsx
> refactor: ローディング

- backend/src/__init__.py
- backend/src/cruds/__init__.py
- backend/src/cruds/image.py
- backend/src/cruds/monster.py
- backend/src/db.py
- backend/src/models/image.py
- backend/src/models/user.py
- backend/src/routers/__init__.py
- backend/src/routers/extract.py
- backend/src/routers/monster.py
- backend/src/routers/silhouette.py
- backend/src/types/__init__.py
- backend/src/types/extract.py
- backend/src/utils.py
- frontend/src/app/confirm-silhouette/page.tsx
- frontend/src/app/take-picture/page.tsx
> 撮影画像の物体抽出アルゴリズム

- backend/src/core/merge_silhouettes.py
- backend/src/models/silhouette.py
- backend/src/routers/picture.py
- backend/src/utils.py
- frontend/src/app/confirm-silhouette/page.tsx
> 抽出画像でシルエットを更新する

- frontend/src/app/level-select/ModalContent.tsx
- frontend/src/app/level-select/Swiper.tsx
- frontend/src/app/level-select/page.tsx
> スマホの画面サイズに対応できるようにしました。

- frontend/src/app/level-select/Swiper.tsx
- frontend/src/app/level-select/page.tsx
> 画面の縦幅に合わせてコンテンツを伸縮させる

- frontend/package.json
- frontend/src/app/level-select/ModalContent.tsx
- frontend/src/app/level-select/Swiper.tsx
- frontend/yarn.lock
> level-select ページ リファクタリング

- frontend/src/app/confirm-silhouette/page.tsx
- frontend/src/app/level-select/ModalContent.tsx
- frontend/src/app/level-select/page.tsx
- frontend/src/app/page.tsx
- frontend/src/app/select-silhouette/page.tsx
> `Stack` を `Centering` に置き換え

- frontend/src/app/confirm-silhouette/page.tsx
- frontend/src/app/level-select/ModalContent.tsx
- frontend/src/app/level-select/Swiper.tsx
- frontend/src/app/select-silhouette/page.tsx
- frontend/src/app/take-picture/page.tsx
- frontend/src/components/Image.tsx
> 画像用コンポーネントを作成

- frontend/src/app/select-silhouette/page.tsx
> select-silhouette ページの Image コンポーネントを修正

- frontend/src/app/naming-monster/page.tsx
> Naming monster

- backend/src/core/merge_silhouettes.py
- frontend/src/app/confirm-silhouette/page.tsx
- frontend/src/app/level-select/ModalContent.tsx
- frontend/src/app/select-silhouette/page.tsx
- frontend/src/components/LinkButton.tsx
> シルエット選択画面から名前付け画面への遷移

- backend/src/core/merge_silhouettes.py
> モンスターベース画像とシルエット画像の統合で、シルエット画像の上にモンスターベース画像を重ねるように変更

- backend/src/db.py
> シルエット画像の DB への登録順をファイル名順にする

- frontend/src/app/player-lobby/page.tsx
> ロビーのページを作成しました。

- frontend/src/app/create-room/page.tsx
- frontend/src/app/player-lobby/page.tsx
ロビーから遷移するURLを追加しました。
close #129
> へやをつくるページを作成しました。

- frontend/src/app/enter-room/page.tsx
IDを４桁までの数字しか入力できないようにしました。
close #130
> 対戦部屋に入る画面を作成しました。

- backend/src/cruds/__init__.py
- backend/src/cruds/monster.py
- backend/src/routers/__init__.py
- backend/src/routers/monster.py
- backend/src/types/__init__.py
- backend/src/types/monster.py
- frontend/src/app/(create-phase)/level-select/Content.tsx
- frontend/src/app/(create-phase)/level-select/Swiper.tsx
- frontend/src/app/(create-phase)/level-select/page.tsx
> レベルセレクト画面でのモンスターの読み込みを1体ずつ非同期に読み込むようにする

- backend/src/core/merge_silhouettes.py
- backend/src/cruds/__init__.py
- backend/src/cruds/user.py
- backend/src/cruds/user_monster.py
- backend/src/db.py
- backend/src/main.py
- backend/src/models/__init__.py
- backend/src/models/user.py
- backend/src/models/user_monster.py
- backend/src/routers/__init__.py
- backend/src/routers/monster.py
- backend/src/routers/picture.py
- backend/src/routers/user.py
- backend/src/routers/user_monster.py
- backend/src/types/__init__.py
- backend/src/types/user.py
- backend/src/types/user_monster.py
- frontend/src/app/(create-phase)/naming-monster/page.tsx
- frontend/src/middleware.ts
> ユーザー認証・識別周り実装

- frontend/src/app/(battle-phase)/battle-attack-select/AttackCenter.tsx
- frontend/src/app/(battle-phase)/battle-attack-select/Field.tsx
- frontend/src/app/(battle-phase)/battle-attack-select/GtpButton.tsx
- frontend/src/app/(battle-phase)/battle-attack-select/HpCalculateCenter.tsx
- frontend/src/app/(battle-phase)/battle-attack-select/page.tsx
> Fix battle attack select

- frontend/src/app/(battle-phase)/match-waiting/page.tsx
> 150 fix matchi waiting

- backend/src/routers/picture.py
- backend/src/types/picture.py
- frontend/src/app/(create-phase)/confirm-silhouette/page.tsx
> 撮影後画面に一致率を表示させる

- backend/src/db.py
- backend/src/routers/silhouette.py
- frontend/src/app/(create-phase)/take-picture/page.tsx
> 一致率 0% 時にエラー

- websocket/websocket.ts
> websocket の連想配列 users の蓄積を解消（バトルが終了したら削除する）

- frontend/src/app/(battle-phase)/(battle)/battle/page.tsx
- frontend/src/components/SocketProvider.tsx
- websocket/websocket.ts
> バトル画面エラー処理

- frontend/src/app/(battle-phase)/(battle)/battle/Field.tsx
> Field の不要な Props を削除

- frontend/next.config.js
> Next.js public ディレクトリ下の静的ファイルにキャッシュを設定

- backend/src/core/check_user.py
- frontend/src/app/(create-phase)/level-select/page.tsx
> レベル選択画面で user_token が存在しない時にエラーメッセージを表示

- frontend/src/app/(battle-phase)/enter-room/page.tsx
> キーボードについて修正しました。

- frontend/src/app/(battle-phase)/(battle)/battle-result/page.tsx
> router.push() をサーバーサイドで実行しないよう修正

- frontend/src/app/(create-phase)/view-details/page.tsx
> frontend/src/app/(create-phase)/view-details/page.tsx に "use client" を付与

- frontend/src/app/page.tsx
> タイトル画面 フォントサイズ調整

- frontend/public/locales/en.json
- frontend/public/locales/ja.json
- frontend/public/locales/ko.json
- frontend/public/locales/zh.json
- frontend/src/app/(battle-phase)/enter-room/page.tsx
- frontend/src/consts.ts
> enter_room エラーメッセージ出す

- frontend/src/app/(battle-phase)/(battle)/battle/page.tsx
> 負けて終了した場合に、結果画面に表示される HP が1ターン前のものになっている

- Makefile
- frontend/src/app/(battle-phase)/(battle)/battle-result/page.tsx
- frontend/src/app/(battle-phase)/(battle)/battle/page.tsx
- frontend/src/app/(battle-phase)/monster-select/ModalContent.tsx
> バトルで一方がモンスター選択後、戻って選び直している間にもう一方がモンスターを選択するとバトルが進行してしまう

- frontend/src/app/(battle-phase)/(battle)/battle/Field.tsx
- frontend/src/app/(battle-phase)/(battle)/battle/page.tsx
- frontend/src/app/(battle-phase)/create-room/page.tsx
- frontend/src/app/(battle-phase)/enter-room/page.tsx
- frontend/src/components/Animation.tsx
> バトル アニメーション・エフェクト

- frontend/package.json
- frontend/src/app/(battle-phase)/(battle)/battle-result/page.tsx
- frontend/yarn.lock
> 結果画面で勝者側に紙吹雪

- backend/src/__init__.py
- backend/src/cruds/user_monster.py
- backend/src/utils.py
> シルエットが2つの時、3つ目のじゃんけんの手は10-90の間でランダムな値を設定する

- backend/src/cruds/__init__.py
- backend/src/cruds/user_monster.py
- backend/src/routers/user.py
- frontend/src/app/(battle-phase)/(battle)/battle/page.tsx
- frontend/src/app/(battle-phase)/monster-select/Content.tsx
> 撮影したモンスターがいないときも遊べるようにする
